### PR TITLE
Update instructions with latest checkout actions version

### PR DESCRIPTION
**Pull request by Saicheg**
Hi!

First of all - huge thanks for you awesome library, it looks great.

I am currently transferring my existing CircleCI config to Github Actions, and during the transition of pronto I found out that on `actions/checkout@v1` got some very surprising bug with update git submodules under my project. We use git submodules to keep rubocop and other configurations the same across all projects in our company.

So digging a bit around I managed to make current actions to be compatible with `actions/checkout@v2`. So thought you would love to try it yourself and keep instructions for latest version under README.

### CODE REVIEW

**Comment by jbielick** [comment]
I, too, had issues with submodules! I was surprised to see the default was a full, recursive checkout. Glad they have a new version. 

Could you describe each of the steps, here, for my understanding?

```yaml
    # checkout commit SHA or merge commit for a PR
    - uses: actions/checkout@v2
      with:
        # checkout all commits in history — is this necessary? or can we get just the last one (default)?
        fetch-depth: 0
    - run: |
        # fetch all branches — what is this for? so that any branch could be a target of pronto compare?
        git fetch --no-tags --prune origin
```

**Comment by Saicheg** [comment]
@jbielick for sure!

Basically, there are 2 tweaks over here:
---
```
fetch-depth: 0
```
Since version 2 is optimized to get just the last commit, we want to tell them to get a full history, otherwise pronto fails with exception of not looking for latest commit message. Here is an error i was seeing:
```
/usr/local/bundle/ruby/2.5.0/gems/pronto-0.10.0/lib/pronto/git/repository.rb:87:in `merge_base': object not found - no match for id (8bfe7d620514429e460ab1667e1a6bb225049830) (Rugged::OdbError)
	from /usr/local/bundle/ruby/2.5.0/gems/pronto-0.10.0/lib/pronto/git/repository.rb:87:in `merge_base'
	from /usr/local/bundle/ruby/2.5.0/gems/pronto-0.10.0/lib/pronto/git/repository.rb:17:in `diff'
	from /usr/local/bundle/ruby/2.5.0/gems/pronto-0.10.0/lib/pronto.rb:62:in `run'
	from /usr/local/bundle/ruby/2.5.0/gems/pronto-0.10.0/lib/pronto/cli.rb:66:in `block in run'
	from /usr/local/bundle/ruby/2.5.0/gems/pronto-0.10.0/lib/pronto/cli.rb:64:in `chdir'
	from /usr/local/bundle/ruby/2.5.0/gems/pronto-0.10.0/lib/pronto/cli.rb:64:in `run'
	from /usr/local/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /runner/pronto:41:in `block in <main>'
	from /runner/pronto:40:in `chdir'
	from /runner/pronto:40:in `<main>'
```
---
```
git fetch --no-tags --prune origin
```
This one is needed to get a diff with `origin/master`, since we fail to compare otherwise. Probably it makes more sense to fetch only master, but it's up on people on what branch they could compare.

**Comment by jbielick** [comment]
@Saicheg Thank you for the extra info.

I, personally, appreciate the finer-tuned controls here and may use them. For the average user, I wouldn't expect submodule recursion to be an issue. So I'm left wondering, for simplicity's sake, should the README continue to show the simplest implementation (`checkout@v1`) and have an additional section mentioning more fine-grained controls with `checkout@v2`?

**Comment by Saicheg** [comment]
@jbielick Agree. Please see my updated PR with additional instructions on README.

**Comment by jbielick** [comment]
Thank you!

**Pull request merged**
