### PR TITLE
Add rails_data_schema check

### PR DESCRIPTION
**Pull request by mbajur**
https://github.com/mbajur/pronto-rails_data_schema

### CODE REVIEW

**Comment by jbielick** [comment]
Hey @mbajur . Thanks for the PR. Could you run `bundle` so the Gemfile.lock gets updated?

**Comment by mbajur** [comment]
@jbielick oh right, completely forgot about that. Done ✅

**Comment by mbajur** [comment]
Is that possible to use the new check right away ?

**Comment by jbielick** [comment]
This is now available in `v.2.4` https://github.com/AdWerx/pronto-ruby/releases/tag/v2.4

**Pull request merged**
